create external schema external_data_modeling 			
from data catalog 			
database 'external_data_modeling' 			
iam_role 'arn:aws:iam::171874763805:role/CSE-Redshift-Spectrum-Role'			
create external database if not exists;			
			
grant usage on schema external_data_modeling to group bi;			
grant usage on schema external_data_modeling to group ba;			
			
drop  table if exists external_data_modeling.property;			
create external table external_data_modeling.property(			
modeldata_id	INTEGER ,		
systemidstart	INTEGER ,		
systemidend	INTEGER ,		
cal_year	INTEGER ,		
startdate	DATE ,		
enddate	TIMESTAMP ,		
startdatetm	TIMESTAMP ,		
enddatetm	TIMESTAMP ,		
ecy	NUMERIC(25,	4)	,
cova_ep	NUMERIC(38,	6)	,
covb_ep	NUMERIC(38,	6)	,
covc_ep	NUMERIC(38,	6)	,
covd_ep	NUMERIC(38,	6)	,
cove_ep	NUMERIC(38,	6)	,
covf_ep	NUMERIC(38,	6)	,
policynumber	VARCHAR(50) ,		
policy_uniqueid	VARCHAR(100) ,		
inceptiondt	TIMESTAMP ,		
policyterm	VARCHAR(10) ,		
policytype	VARCHAR(7) ,		
effectivedate	DATE ,		
expirationdate	DATE ,		
policystate	VARCHAR(50) ,		
policyform	VARCHAR(255) ,		
persistencydiscountdt	DATE ,		
persistency	INTEGER ,		
companycd	VARCHAR(50) ,		
carriercd	VARCHAR(100) ,		
installmentfee	VARCHAR(255) ,		
nsffee	VARCHAR(255) ,		
latefee	VARCHAR(255) ,		
programind	VARCHAR(255) ,		
cseemployeediscountind	VARCHAR(255) ,		
liabilitylimitolt	VARCHAR(20) ,		
liabilitylimitcpl	VARCHAR(255) ,		
personalinjuryind	VARCHAR(765) ,		
producercode	VARCHAR(50) ,		
producername	VARCHAR(255) ,		
produceraddress	VARCHAR(510) ,		
producercity	VARCHAR(80) ,		
producerstate	VARCHAR(50) ,		
producerpostalcode	VARCHAR(20) ,		
producer_status	VARCHAR(10) ,		
territory	VARCHAR(50) ,		
risk_uniqueid	VARCHAR(100) ,		
risknumber	INTEGER ,		
risktype	VARCHAR(255) ,		
state	VARCHAR(255) ,		
county	VARCHAR(255) ,		
postalcode	VARCHAR(255) ,		
city	VARCHAR(255) ,		
addr1	VARCHAR(255) ,		
addr2	VARCHAR(255) ,		
building_uniqueid	VARCHAR(255) ,		
yearbuilt	INTEGER ,		
sqft	INTEGER ,		
stories	INTEGER ,		
roofcd	VARCHAR(255) ,		
units	INTEGER ,		
occupancycd	VARCHAR(255) ,		
allperilded	VARCHAR(255) ,		
waterded	VARCHAR(16) ,		
protectionclass	VARCHAR(255) ,		
constructioncd	VARCHAR(255) ,		
reportedfirelineassessment	VARCHAR(255) ,		
firehazardscore	VARCHAR(255) ,		
reportedfirehazardscore	VARCHAR(255) ,		
multipolicyind	VARCHAR(765) ,		
multipolicynumber	VARCHAR(255) ,		
multipolicyindumbrella	VARCHAR(765) ,		
multipolicynumberumbrella	VARCHAR(255) ,		
earthquakeumbrellaind	VARCHAR(9) ,		
usagetype	VARCHAR(255) ,		
secondaryresidence	VARCHAR(3) ,		
ordinanceorlawpct	INTEGER ,		
functionalreplacementcost	VARCHAR(4) ,		
homegardcreditind	VARCHAR(765) ,		
sprinklersystem	VARCHAR(765) ,		
landlordind	VARCHAR(765) ,		
cseagent	VARCHAR(9) ,		
rentersinsurance	VARCHAR(9) ,		
firealarmtype	VARCHAR(765) ,		
burglaryalarmtype	VARCHAR(765) ,		
waterdetectiondevice	VARCHAR(9) ,		
neighborhoodcrimewatchind	VARCHAR(765) ,		
propertymanager	VARCHAR(9) ,		
safeguardplusind	VARCHAR(765) ,		
deluxepackageind	VARCHAR(9) ,		
ratingtier	VARCHAR(255) ,		
wuiclass	VARCHAR(30) ,		
kitchenfireextinguisherind	VARCHAR(765) ,		
smokedetector	VARCHAR(765) ,		
gatedcommunityind	VARCHAR(765) ,		
deadboltind	VARCHAR(765) ,		
poolind	VARCHAR(765) ,		
replacementcostdwellingind	VARCHAR(765) ,		
replacementvalueind	VARCHAR(765) ,		
serviceline	VARCHAR(12) ,		
equipmentbreakdown	VARCHAR(765) ,		
tenantevictions	VARCHAR(765) ,		
lossassessment	VARCHAR(16) ,		
numberoffamilies	INTEGER ,		
insuredfirstname	VARCHAR(200) ,		
insuredlastname	VARCHAR(200) ,		
insureddob	TIMESTAMP ,		
insuredage	BIGINT ,		
maritalstatus	VARCHAR(256) ,		
insurancescore	VARCHAR(255) ,		
overriddeninsurancescore	VARCHAR(255) ,		
insurancescorevalue	VARCHAR(5) ,		
ratepageeffectivedt	TIMESTAMP ,		
insscoretiervalueband	VARCHAR(20) ,		
applieddt	DATE ,		
financialstabilitytier	VARCHAR(20) ,		
allcov_wp	NUMERIC(38,	2)	,
allcov_lossinc	NUMERIC(38,	2)	,
allcov_lossdcce	NUMERIC(38,	2)	,
allcov_lossalae	NUMERIC(38,	2)	,
cova_wp	NUMERIC(38,	2)	,
covb_wp	NUMERIC(38,	2)	,
covc_wp	NUMERIC(38,	2)	,
covd_wp	NUMERIC(38,	2)	,
cove_wp	NUMERIC(38,	2)	,
covf_wp	NUMERIC(38,	2)	,
cova_deductible	VARCHAR(255) ,		
covb_deductible	VARCHAR(255) ,		
covc_deductible	VARCHAR(255) ,		
covd_deductible	VARCHAR(255) ,		
cove_deductible	VARCHAR(255) ,		
covf_deductible	VARCHAR(255) ,		
cova_limit	VARCHAR(255) ,		
covb_limit	VARCHAR(255) ,		
covc_limit	VARCHAR(255) ,		
covcincreasedlimit	INTEGER ,		
covd_limit	VARCHAR(255) ,		
cove_limit	VARCHAR(255) ,		
covf_limit	VARCHAR(255) ,		
onpremises_theft_limit	VARCHAR(255) ,		
awayfrompremises_theft_limit	VARCHAR(255) ,		
quality_polappinconsistency_flg	VARCHAR(3) ,		
quality_riskidduplicates_flg	VARCHAR(3) ,		
quality_claimok_flg	INTEGER ,		
quality_claimpolicytermjoin_flg	INTEGER ,		
covabcdefliab_loss	NUMERIC(38,	2)	,
covabcdefliab_claim_count	INTEGER ,		
cat_covabcdefliab_loss	NUMERIC(38,	2)	,
cat_covabcdefliab_claim_count	INTEGER ,		
cova_il_nc_water	NUMERIC(38,	2)	,
cova_il_nc_wh	NUMERIC(38,	2)	,
cova_il_nc_tv	NUMERIC(38,	2)	,
cova_il_nc_fl	NUMERIC(38,	2)	,
cova_il_nc_ao	NUMERIC(38,	2)	,
cova_il_cat_fire	NUMERIC(38,	2)	,
cova_il_cat_ao	NUMERIC(38,	2)	,
covb_il_nc_water	NUMERIC(38,	2)	,
covb_il_nc_wh	NUMERIC(38,	2)	,
covb_il_nc_tv	NUMERIC(38,	2)	,
covb_il_nc_fl	NUMERIC(38,	2)	,
covb_il_nc_ao	NUMERIC(38,	2)	,
covb_il_cat_fire	NUMERIC(38,	2)	,
covb_il_cat_ao	NUMERIC(38,	2)	,
covc_il_nc_water	NUMERIC(38,	2)	,
covc_il_nc_wh	NUMERIC(38,	2)	,
covc_il_nc_tv	NUMERIC(38,	2)	,
covc_il_nc_fl	NUMERIC(38,	2)	,
covc_il_nc_ao	NUMERIC(38,	2)	,
covc_il_cat_fire	NUMERIC(38,	2)	,
covc_il_cat_ao	NUMERIC(38,	2)	,
covd_il_nc_water	NUMERIC(38,	2)	,
covd_il_nc_wh	NUMERIC(38,	2)	,
covd_il_nc_tv	NUMERIC(38,	2)	,
covd_il_nc_fl	NUMERIC(38,	2)	,
covd_il_nc_ao	NUMERIC(38,	2)	,
covd_il_cat_fire	NUMERIC(38,	2)	,
covd_il_cat_ao	NUMERIC(38,	2)	,
cove_il_nc_water	NUMERIC(38,	2)	,
cove_il_nc_wh	NUMERIC(38,	2)	,
cove_il_nc_tv	NUMERIC(38,	2)	,
cove_il_nc_fl	NUMERIC(38,	2)	,
cove_il_nc_ao	NUMERIC(38,	2)	,
cove_il_cat_fire	NUMERIC(38,	2)	,
cove_il_cat_ao	NUMERIC(38,	2)	,
covf_il_nc_water	NUMERIC(38,	2)	,
covf_il_nc_wh	NUMERIC(38,	2)	,
covf_il_nc_tv	NUMERIC(38,	2)	,
covf_il_nc_fl	NUMERIC(38,	2)	,
covf_il_nc_ao	NUMERIC(38,	2)	,
covf_il_cat_fire	NUMERIC(38,	2)	,
covf_il_cat_ao	NUMERIC(38,	2)	,
liab_il_nc_water	NUMERIC(38,	2)	,
liab_il_nc_wh	NUMERIC(38,	2)	,
liab_il_nc_tv	NUMERIC(38,	2)	,
liab_il_nc_fl	NUMERIC(38,	2)	,
liab_il_nc_ao	NUMERIC(38,	2)	,
liab_il_cat_fire	NUMERIC(38,	2)	,
liab_il_cat_ao	NUMERIC(38,	2)	,
cova_il_dcce_nc_water	NUMERIC(38,	2)	,
cova_il_dcce_nc_wh	NUMERIC(38,	2)	,
cova_il_dcce_nc_tv	NUMERIC(38,	2)	,
cova_il_dcce_nc_fl	NUMERIC(38,	2)	,
cova_il_dcce_nc_ao	NUMERIC(38,	2)	,
cova_il_dcce_cat_fire	NUMERIC(38,	2)	,
cova_il_dcce_cat_ao	NUMERIC(38,	2)	,
covb_il_dcce_nc_water	NUMERIC(38,	2)	,
covb_il_dcce_nc_wh	NUMERIC(38,	2)	,
covb_il_dcce_nc_tv	NUMERIC(38,	2)	,
covb_il_dcce_nc_fl	NUMERIC(38,	2)	,
covb_il_dcce_nc_ao	NUMERIC(38,	2)	,
covb_il_dcce_cat_fire	NUMERIC(38,	2)	,
covb_il_dcce_cat_ao	NUMERIC(38,	2)	,
covc_il_dcce_nc_water	NUMERIC(38,	2)	,
covc_il_dcce_nc_wh	NUMERIC(38,	2)	,
covc_il_dcce_nc_tv	NUMERIC(38,	2)	,
covc_il_dcce_nc_fl	NUMERIC(38,	2)	,
covc_il_dcce_nc_ao	NUMERIC(38,	2)	,
covc_il_dcce_cat_fire	NUMERIC(38,	2)	,
covc_il_dcce_cat_ao	NUMERIC(38,	2)	,
covd_il_dcce_nc_water	NUMERIC(38,	2)	,
covd_il_dcce_nc_wh	NUMERIC(38,	2)	,
covd_il_dcce_nc_tv	NUMERIC(38,	2)	,
covd_il_dcce_nc_fl	NUMERIC(38,	2)	,
covd_il_dcce_nc_ao	NUMERIC(38,	2)	,
covd_il_dcce_cat_fire	NUMERIC(38,	2)	,
covd_il_dcce_cat_ao	NUMERIC(38,	2)	,
cove_il_dcce_nc_water	NUMERIC(38,	2)	,
cove_il_dcce_nc_wh	NUMERIC(38,	2)	,
cove_il_dcce_nc_tv	NUMERIC(38,	2)	,
cove_il_dcce_nc_fl	NUMERIC(38,	2)	,
cove_il_dcce_nc_ao	NUMERIC(38,	2)	,
cove_il_dcce_cat_fire	NUMERIC(38,	2)	,
cove_il_dcce_cat_ao	NUMERIC(38,	2)	,
covf_il_dcce_nc_water	NUMERIC(38,	2)	,
covf_il_dcce_nc_wh	NUMERIC(38,	2)	,
covf_il_dcce_nc_tv	NUMERIC(38,	2)	,
covf_il_dcce_nc_fl	NUMERIC(38,	2)	,
covf_il_dcce_nc_ao	NUMERIC(38,	2)	,
covf_il_dcce_cat_fire	NUMERIC(38,	2)	,
covf_il_dcce_cat_ao	NUMERIC(38,	2)	,
liab_il_dcce_nc_water	NUMERIC(38,	2)	,
liab_il_dcce_nc_wh	NUMERIC(38,	2)	,
liab_il_dcce_nc_tv	NUMERIC(38,	2)	,
liab_il_dcce_nc_fl	NUMERIC(38,	2)	,
liab_il_dcce_nc_ao	NUMERIC(38,	2)	,
liab_il_dcce_cat_fire	NUMERIC(38,	2)	,
liab_il_dcce_cat_ao	NUMERIC(38,	2)	,
cova_il_alae_nc_water	NUMERIC(38,	2)	,
cova_il_alae_nc_wh	NUMERIC(38,	2)	,
cova_il_alae_nc_tv	NUMERIC(38,	2)	,
cova_il_alae_nc_fl	NUMERIC(38,	2)	,
cova_il_alae_nc_ao	NUMERIC(38,	2)	,
cova_il_alae_cat_fire	NUMERIC(38,	2)	,
cova_il_alae_cat_ao	NUMERIC(38,	2)	,
covb_il_alae_nc_water	NUMERIC(38,	2)	,
covb_il_alae_nc_wh	NUMERIC(38,	2)	,
covb_il_alae_nc_tv	NUMERIC(38,	2)	,
covb_il_alae_nc_fl	NUMERIC(38,	2)	,
covb_il_alae_nc_ao	NUMERIC(38,	2)	,
covb_il_alae_cat_fire	NUMERIC(38,	2)	,
covb_il_alae_cat_ao	NUMERIC(38,	2)	,
covc_il_alae_nc_water	NUMERIC(38,	2)	,
covc_il_alae_nc_wh	NUMERIC(38,	2)	,
covc_il_alae_nc_tv	NUMERIC(38,	2)	,
covc_il_alae_nc_fl	NUMERIC(38,	2)	,
covc_il_alae_nc_ao	NUMERIC(38,	2)	,
covc_il_alae_cat_fire	NUMERIC(38,	2)	,
covc_il_alae_cat_ao	NUMERIC(38,	2)	,
covd_il_alae_nc_water	NUMERIC(38,	2)	,
covd_il_alae_nc_wh	NUMERIC(38,	2)	,
covd_il_alae_nc_tv	NUMERIC(38,	2)	,
covd_il_alae_nc_fl	NUMERIC(38,	2)	,
covd_il_alae_nc_ao	NUMERIC(38,	2)	,
covd_il_alae_cat_fire	NUMERIC(38,	2)	,
covd_il_alae_cat_ao	NUMERIC(38,	2)	,
cove_il_alae_nc_water	NUMERIC(38,	2)	,
cove_il_alae_nc_wh	NUMERIC(38,	2)	,
cove_il_alae_nc_tv	NUMERIC(38,	2)	,
cove_il_alae_nc_fl	NUMERIC(38,	2)	,
cove_il_alae_nc_ao	NUMERIC(38,	2)	,
cove_il_alae_cat_fire	NUMERIC(38,	2)	,
cove_il_alae_cat_ao	NUMERIC(38,	2)	,
covf_il_alae_nc_water	NUMERIC(38,	2)	,
covf_il_alae_nc_wh	NUMERIC(38,	2)	,
covf_il_alae_nc_tv	NUMERIC(38,	2)	,
covf_il_alae_nc_fl	NUMERIC(38,	2)	,
covf_il_alae_nc_ao	NUMERIC(38,	2)	,
covf_il_alae_cat_fire	NUMERIC(38,	2)	,
covf_il_alae_cat_ao	NUMERIC(38,	2)	,
liab_il_alae_nc_water	NUMERIC(38,	2)	,
liab_il_alae_nc_wh	NUMERIC(38,	2)	,
liab_il_alae_nc_tv	NUMERIC(38,	2)	,
liab_il_alae_nc_fl	NUMERIC(38,	2)	,
liab_il_alae_nc_ao	NUMERIC(38,	2)	,
liab_il_alae_cat_fire	NUMERIC(38,	2)	,
liab_il_alae_cat_ao	NUMERIC(38,	2)	,
cova_ic_nc_water	INTEGER ,		
cova_ic_nc_wh	INTEGER ,		
cova_ic_nc_tv	INTEGER ,		
cova_ic_nc_fl	INTEGER ,		
cova_ic_nc_ao	INTEGER ,		
cova_ic_cat_fire	INTEGER ,		
cova_ic_cat_ao	INTEGER ,		
covb_ic_nc_water	INTEGER ,		
covb_ic_nc_wh	INTEGER ,		
covb_ic_nc_tv	INTEGER ,		
covb_ic_nc_fl	INTEGER ,		
covb_ic_nc_ao	INTEGER ,		
covb_ic_cat_fire	INTEGER ,		
covb_ic_cat_ao	INTEGER ,		
covc_ic_nc_water	INTEGER ,		
covc_ic_nc_wh	INTEGER ,		
covc_ic_nc_tv	INTEGER ,		
covc_ic_nc_fl	INTEGER ,		
covc_ic_nc_ao	INTEGER ,		
covc_ic_cat_fire	INTEGER ,		
covc_ic_cat_ao	INTEGER ,		
covd_ic_nc_water	INTEGER ,		
covd_ic_nc_wh	INTEGER ,		
covd_ic_nc_tv	INTEGER ,		
covd_ic_nc_fl	INTEGER ,		
covd_ic_nc_ao	INTEGER ,		
covd_ic_cat_fire	INTEGER ,		
covd_ic_cat_ao	INTEGER ,		
cove_ic_nc_water	INTEGER ,		
cove_ic_nc_wh	INTEGER ,		
cove_ic_nc_tv	INTEGER ,		
cove_ic_nc_fl	INTEGER ,		
cove_ic_nc_ao	INTEGER ,		
cove_ic_cat_fire	INTEGER ,		
cove_ic_cat_ao	INTEGER ,		
covf_ic_nc_water	INTEGER ,		
covf_ic_nc_wh	INTEGER ,		
covf_ic_nc_tv	INTEGER ,		
covf_ic_nc_fl	INTEGER ,		
covf_ic_nc_ao	INTEGER ,		
covf_ic_cat_fire	INTEGER ,		
covf_ic_cat_ao	INTEGER ,		
liab_ic_nc_water	INTEGER ,		
liab_ic_nc_wh	INTEGER ,		
liab_ic_nc_tv	INTEGER ,		
liab_ic_nc_fl	INTEGER ,		
liab_ic_nc_ao	INTEGER ,		
liab_ic_cat_fire	INTEGER ,		
liab_ic_cat_ao	INTEGER ,		
cova_ic_dcce_nc_water	INTEGER ,		
cova_ic_dcce_nc_wh	INTEGER ,		
cova_ic_dcce_nc_tv	INTEGER ,		
cova_ic_dcce_nc_fl	INTEGER ,		
cova_ic_dcce_nc_ao	INTEGER ,		
cova_ic_dcce_cat_fire	INTEGER ,		
cova_ic_dcce_cat_ao	INTEGER ,		
covb_ic_dcce_nc_water	INTEGER ,		
covb_ic_dcce_nc_wh	INTEGER ,		
covb_ic_dcce_nc_tv	INTEGER ,		
covb_ic_dcce_nc_fl	INTEGER ,		
covb_ic_dcce_nc_ao	INTEGER ,		
covb_ic_dcce_cat_fire	INTEGER ,		
covb_ic_dcce_cat_ao	INTEGER ,		
covc_ic_dcce_nc_water	INTEGER ,		
covc_ic_dcce_nc_wh	INTEGER ,		
covc_ic_dcce_nc_tv	INTEGER ,		
covc_ic_dcce_nc_fl	INTEGER ,		
covc_ic_dcce_nc_ao	INTEGER ,		
covc_ic_dcce_cat_fire	INTEGER ,		
covc_ic_dcce_cat_ao	INTEGER ,		
covd_ic_dcce_nc_water	INTEGER ,		
covd_ic_dcce_nc_wh	INTEGER ,		
covd_ic_dcce_nc_tv	INTEGER ,		
covd_ic_dcce_nc_fl	INTEGER ,		
covd_ic_dcce_nc_ao	INTEGER ,		
covd_ic_dcce_cat_fire	INTEGER ,		
covd_ic_dcce_cat_ao	INTEGER ,		
covf_ic_dcce_nc_water	INTEGER ,		
covf_ic_dcce_nc_wh	INTEGER ,		
covf_ic_dcce_nc_tv	INTEGER ,		
covf_ic_dcce_nc_fl	INTEGER ,		
covf_ic_dcce_nc_ao	INTEGER ,		
covf_ic_dcce_cat_fire	INTEGER ,		
covf_ic_dcce_cat_ao	INTEGER ,		
liab_ic_dcce_nc_water	INTEGER ,		
liab_ic_dcce_nc_wh	INTEGER ,		
liab_ic_dcce_nc_tv	INTEGER ,		
liab_ic_dcce_nc_fl	INTEGER ,		
liab_ic_dcce_nc_ao	INTEGER ,		
liab_ic_dcce_cat_fire	INTEGER ,		
liab_ic_dcce_cat_ao	INTEGER ,		
cova_ic_alae_nc_water	INTEGER ,		
cova_ic_alae_nc_wh	INTEGER ,		
cova_ic_alae_nc_tv	INTEGER ,		
cova_ic_alae_nc_fl	INTEGER ,		
cova_ic_alae_nc_ao	INTEGER ,		
cova_ic_alae_cat_fire	INTEGER ,		
cova_ic_alae_cat_ao	INTEGER ,		
covb_ic_alae_nc_water	INTEGER ,		
covb_ic_alae_nc_wh	INTEGER ,		
covb_ic_alae_nc_tv	INTEGER ,		
covb_ic_alae_nc_fl	INTEGER ,		
covb_ic_alae_nc_ao	INTEGER ,		
covb_ic_alae_cat_fire	INTEGER ,		
covb_ic_alae_cat_ao	INTEGER ,		
covc_ic_alae_nc_water	INTEGER ,		
covc_ic_alae_nc_wh	INTEGER ,		
covc_ic_alae_nc_tv	INTEGER ,		
covc_ic_alae_nc_fl	INTEGER ,		
covc_ic_alae_nc_ao	INTEGER ,		
covc_ic_alae_cat_fire	INTEGER ,		
covc_ic_alae_cat_ao	INTEGER ,		
covd_ic_alae_nc_water	INTEGER ,		
covd_ic_alae_nc_wh	INTEGER ,		
covd_ic_alae_nc_tv	INTEGER ,		
covd_ic_alae_nc_fl	INTEGER ,		
covd_ic_alae_nc_ao	INTEGER ,		
covd_ic_alae_cat_fire	INTEGER ,		
covd_ic_alae_cat_ao	INTEGER ,		
cove_ic_alae_nc_water	INTEGER ,		
cove_ic_alae_nc_wh	INTEGER ,		
cove_ic_alae_nc_tv	INTEGER ,		
cove_ic_alae_nc_fl	INTEGER ,		
cove_ic_alae_nc_ao	INTEGER ,		
cove_ic_alae_cat_fire	INTEGER ,		
cove_ic_alae_cat_ao	INTEGER ,		
covf_ic_alae_nc_water	INTEGER ,		
covf_ic_alae_nc_wh	INTEGER ,		
covf_ic_alae_nc_tv	INTEGER ,		
covf_ic_alae_nc_fl	INTEGER ,		
covf_ic_alae_nc_ao	INTEGER ,		
covf_ic_alae_cat_fire	INTEGER ,		
covf_ic_alae_cat_ao	INTEGER ,		
liab_ic_alae_nc_water	INTEGER ,		
liab_ic_alae_nc_wh	INTEGER ,		
liab_ic_alae_nc_tv	INTEGER ,		
liab_ic_alae_nc_fl	INTEGER ,		
liab_ic_alae_nc_ao	INTEGER ,		
liab_ic_alae_cat_fire	INTEGER ,		
liab_ic_alae_cat_ao	INTEGER ,		
cova_fl	INTEGER ,		
cova_sf	INTEGER ,		
cova_ec	INTEGER ,		
covc_fl	INTEGER ,		
covc_sf	INTEGER ,		
covc_ec	INTEGER ,		
loaddate	TIMESTAMP ,		
customer_cnt_active_policies	BIGINT ,		
hascreditcardpaymentbyinsured	VARCHAR(3) ,		
hascheckpaymentbyinsured	VARCHAR(3) ,		
haspaymentbyother	VARCHAR(3) 		
)			
partitioned by (month_id INTEGER)			
stored as PARQUET			
location  's3://cse-bi/RedshiftSpectrum/Modeling/Property/'			
TABLE PROPERTIES ( 'write.parallel'='on' );			
 			
/*			
insert into external_data_modeling.property			
select *, cast(to_char(ADD_MONTHS(GetDate(),-1),'yyyymm') as int) month_id from fsbi_dw_spinn.vproperty_modeldata_allcov			
			
ALTER TABLE external_data_modeling.property DROP PARTITION  (month_id=202203)			
			
			
			
select month_id, count(*)	,  max(enddatetm) max_enddatetm		
from external_data_modeling.property			
where month_id in (202101,202112, 202201, 202202)			
group by month_id;			
			
			
select  count(*)	,  max(enddatetm) max_enddatetm		
from modeling.vproperty_modeldata_allcov_20220104	;		
			
select  count(*)	,  max(enddatetm) max_enddatetm		
from modeling.vproperty_modeldata_allcov_20220201	;		
			
			
select 			
replace(replace(replace(values,'[',''),']',''),'"','') month_id,			
'select * from external_data_modeling.property where month_id='+cast(month_id as varchar) +' limit 100;'			
from SVV_EXTERNAL_PARTITIONS			
where schemaname='external_data_modeling'			
and tablename='property'			
order by month_id			

*/

drop  table if exists external_data_modeling.auto;					
					
create external table external_data_modeling.auto(					
policynumber	VARCHAR(50) ,				
policy_uniqueid	VARCHAR(20) ,				
vin	VARCHAR(100) ,				
vehicle_uniqueid	VARCHAR(250) ,				
riskcd	INTEGER ,				
risktypecd	VARCHAR(255) ,				
driver	VARCHAR(255) ,				
drivernumber	INTEGER ,				
driverparentid	VARCHAR(250) ,				
cal_year	INTEGER ,				
startdate	DATE ,				
enddate	TIMESTAMP ,				
startdatetm	TIMESTAMP ,				
enddatetm	TIMESTAMP ,				
ecy	NUMERIC(25,	4)	,		
coverage	VARCHAR(6) ,				
limit1	VARCHAR(50) ,				
limit2	VARCHAR(50) ,				
deductible	VARCHAR(50) ,				
wp	NUMERIC(38,	2)	,		
ep	NUMERIC(38,	6)	,		
coll_deductible	VARCHAR(50) ,				
comp_deductible	VARCHAR(50) ,				
bi_limit1	VARCHAR(50) ,				
bi_limit2	VARCHAR(50) ,				
umbi_limit1	VARCHAR(50) ,				
umbi_limit2	VARCHAR(50) ,				
pd_limit1	VARCHAR(50) ,				
pd_limit2	VARCHAR(50) ,				
cntveh	INTEGER ,				
cntdrv	INTEGER ,				
cntnondrv	INTEGER ,				
cntexcludeddrv	INTEGER ,				
mindriverage	INTEGER ,				
extra_vehicles	VARCHAR(3) ,				
companycd	VARCHAR(50) ,				
carriercd	VARCHAR(100) ,				
programind	VARCHAR(255) ,				
previouscarriercd	VARCHAR(255) ,				
policyneworrenewal	VARCHAR(7) ,				
renewaltermcd	VARCHAR(255) ,				
effectivedate	DATE ,				
expirationdate	DATE ,				
inceptiondt	TIMESTAMP ,				
persistencydiscountdt	DATE ,				
producercode	VARCHAR(50) ,				
producername	VARCHAR(255) ,				
produceraddress	VARCHAR(510) ,				
producercity	VARCHAR(80) ,				
producerstate	VARCHAR(50) ,				
producerpostalcode	VARCHAR(20) ,				
producer_status	VARCHAR(10) ,				
territory	VARCHAR(50) ,				
multipolicydiscountind	VARCHAR(3) ,				
multipolicydiscountind_value	VARCHAR(255) ,				
homerelatedpolicynumber	VARCHAR(255) ,				
umbrellarelatedpolicynumber	VARCHAR(255) ,				
multicardiscountind	VARCHAR(3) ,				
cseemployeediscountind	VARCHAR(255) ,				
installmentfee	VARCHAR(255) ,				
nsffee	VARCHAR(255) ,				
latefee	VARCHAR(255) ,				
liabilityreductionind	VARCHAR(255) ,				
fullpaydiscountind	VARCHAR(255) ,				
twopaydiscountind	VARCHAR(255) ,				
eftdiscount	VARCHAR(3) ,				
persistency	INTEGER ,				
policyyear	INTEGER ,				
vehicleinceptiondate	DATE ,				
state	VARCHAR(255) ,				
county	VARCHAR(255) ,				
postalcode	VARCHAR(255) ,				
city	VARCHAR(255) ,				
addr1	VARCHAR(1023) ,				
addr2	VARCHAR(255) ,				
garagaddrflg	VARCHAR(3) ,				
garagpostalcode	VARCHAR(255) ,				
garagpostalcodeflg	VARCHAR(3) ,				
vehbodytypecd	VARCHAR(255) ,				
performancecd	VARCHAR(255) ,				
modelyr	VARCHAR(10) ,				
vehusecd	VARCHAR(255) ,				
estimatedannualdistance	INTEGER ,				
estimatedworkdistance	INTEGER ,				
odometerreading	VARCHAR(10) ,				
weekspermonthdriven	VARCHAR(255) ,				
daysperweekdriven	VARCHAR(255) ,				
manufacturer	VARCHAR(255) ,				
neworusedind	VARCHAR(255) ,				
antitheftcd	VARCHAR(255) ,				
restraintcd	VARCHAR(255) ,				
towingandlaborind	VARCHAR(255) ,				
rentalreimbursementind	VARCHAR(255) ,				
medicalpartsaccessibility	VARCHAR(4) ,				
mileage	VARCHAR(12) ,				
titlehistoryissue	VARCHAR(3) ,				
californiarecentmileage	INTEGER ,				
recentaveragemileage	INTEGER ,				
averagemileage	INTEGER ,				
modeledannualmileage	INTEGER ,				
last_owner_average_miles	INTEGER ,				
last_owner_recent_annual_mileage	INTEGER ,				
last_owner_government_recent_annual_mileage	INTEGER ,				
estimated_current_mileage	INTEGER ,				
annual_mileage_estimate	INTEGER ,				
salvage	VARCHAR(3) ,				
matchcarfax	VARCHAR(51) ,				
carfaxsource	VARCHAR(50) ,				
classcd	VARCHAR(255) ,				
ratingvalue	VARCHAR(255) ,				
cmpratingvalue	VARCHAR(255) ,				
colratingvalue	VARCHAR(255) ,				
liabilityratingvalue	VARCHAR(255) ,				
medpayratingvalue	VARCHAR(255) ,				
racmpratingvalue	VARCHAR(255) ,				
racolratingvalue	VARCHAR(255) ,				
rabiratingsymbol	VARCHAR(255) ,				
rapdratingsymbol	VARCHAR(255) ,				
ramedpayratingsymbol	VARCHAR(255) ,				
garageterritory	INTEGER ,				
daylightrunninglightsind	VARCHAR(255) ,				
costnewamt	NUMERIC(28,	6)	,		
statedamt	NUMERIC(28,	6)	,		
statedamtind	VARCHAR(255) ,				
fullglasscovind	VARCHAR(3) ,				
vehicle_value	NUMERIC(28,	6)	,		
liabilityonlyflg	VARCHAR(3) ,				
componlyflg	VARCHAR(3) ,				
driverinceptiondate	DATE ,				
licensenumber	VARCHAR(255) ,				
birthdt	TIMESTAMP ,				
gendercd	VARCHAR(255) ,				
maritalstatuscd	VARCHAR(255) ,				
acci_pointschargedterm	INTEGER ,				
viol_pointschargedterm	INTEGER ,				
susp_pointschargedterm	INTEGER ,				
other_pointschargedterm	INTEGER ,				
driverstatuscd	VARCHAR(255) ,				
drivertypecd	VARCHAR(255) ,				
licensedt	TIMESTAMP ,				
licensedstateprovcd	VARCHAR(255) ,				
newtostateind	VARCHAR(255) ,				
scholasticdiscountind	VARCHAR(255) ,				
gooddriverind	VARCHAR(255) ,				
maturedriverind	VARCHAR(255) ,				
occupationclasscd	VARCHAR(255) ,				
mvrstatusdt	TIMESTAMP ,				
mvrstatus	VARCHAR(255) ,				
newteenexpirationdt	DATE ,				
drivertrainingind	VARCHAR(255) ,				
viol_pointscharged_adj	INTEGER ,				
acci_pointscharged_adj	INTEGER ,				
missedviolationpoints	INTEGER ,				
acci5yr	INTEGER ,				
acci7yr	INTEGER ,				
pointscharged	INTEGER ,				
driverage	BIGINT ,				
driverlicenseage	BIGINT ,				
excess_veh_ind	VARCHAR(3) ,				
insurancescore	VARCHAR(255) ,				
overriddeninsurancescore	VARCHAR(255) ,				
insurancescorevalue	VARCHAR(5) ,				
ratepageeffectivedt	TIMESTAMP ,				
insscoretiervalueband	VARCHAR(20) ,				
applieddt	DATE ,				
financialstabilitytier	VARCHAR(20) ,				
excludeddrvflg	VARCHAR(3) ,				
claim_count_le500	NUMERIC(12,	2)	,		
claim_count_1000	NUMERIC(12,	2)	,		
claim_count_1500	NUMERIC(12,	2)	,		
claim_count_2000	NUMERIC(12,	2)	,		
claim_count_2500	NUMERIC(12,	2)	,		
claim_count_5k	NUMERIC(12,	2)	,		
claim_count_10k	NUMERIC(12,	2)	,		
claim_count_25k	NUMERIC(12,	2)	,		
claim_count_50k	NUMERIC(12,	2)	,		
claim_count_100k	NUMERIC(12,	2)	,		
claim_count_250k	NUMERIC(12,	2)	,		
claim_count_500k	NUMERIC(12,	2)	,		
claim_count_750k	NUMERIC(12,	2)	,		
claim_count_1m	NUMERIC(12,	2)	,		
claim_count	NUMERIC(12,	2)	,		
nc_inc_loss_le500	NUMERIC(38,	2)	,		
nc_inc_loss_1000	NUMERIC(38,	2)	,		
nc_inc_loss_1500	NUMERIC(38,	2)	,		
nc_inc_loss_2000	NUMERIC(38,	2)	,		
nc_inc_loss_2500	NUMERIC(38,	2)	,		
nc_inc_loss_5k	NUMERIC(38,	2)	,		
nc_inc_loss_10k	NUMERIC(38,	2)	,		
nc_inc_loss_25k	NUMERIC(38,	2)	,		
nc_inc_loss_50k	NUMERIC(38,	2)	,		
nc_inc_loss_100k	NUMERIC(38,	2)	,		
nc_inc_loss_250k	NUMERIC(38,	2)	,		
nc_inc_loss_500k	NUMERIC(38,	2)	,		
nc_inc_loss_750k	NUMERIC(38,	2)	,		
nc_inc_loss_1m	NUMERIC(38,	2)	,		
nc_inc_loss	NUMERIC(38,	2)	,		
cat_inc_loss_le500	NUMERIC(38,	2)	,		
cat_inc_loss_1000	NUMERIC(38,	2)	,		
cat_inc_loss_1500	NUMERIC(38,	2)	,		
cat_inc_loss_2000	NUMERIC(38,	2)	,		
cat_inc_loss_2500	NUMERIC(38,	2)	,		
cat_inc_loss_5k	NUMERIC(38,	2)	,		
cat_inc_loss_10k	NUMERIC(38,	2)	,		
cat_inc_loss_25k	NUMERIC(38,	2)	,		
cat_inc_loss_50k	NUMERIC(38,	2)	,		
cat_inc_loss_100k	NUMERIC(38,	2)	,		
cat_inc_loss_250k	NUMERIC(38,	2)	,		
cat_inc_loss_500k	NUMERIC(38,	2)	,		
cat_inc_loss_750k	NUMERIC(38,	2)	,		
cat_inc_loss_1m	NUMERIC(38,	2)	,		
cat_inc_loss	NUMERIC(38,	2)	,		
nc_inc_loss_dcce_le500	NUMERIC(38,	2)	,		
nc_inc_loss_dcce_1000	NUMERIC(38,	2)	,		
nc_inc_loss_dcce_1500	NUMERIC(38,	2)	,		
nc_inc_loss_dcce_2000	NUMERIC(38,	2)	,		
nc_inc_loss_dcce_2500	NUMERIC(38,	2)	,		
nc_inc_loss_dcce_5k	NUMERIC(38,	2)	,		
nc_inc_loss_dcce_10k	NUMERIC(38,	2)	,		
nc_inc_loss_dcce_25k	NUMERIC(38,	2)	,		
nc_inc_loss_dcce_50k	NUMERIC(38,	2)	,		
nc_inc_loss_dcce_100k	NUMERIC(38,	2)	,		
nc_inc_loss_dcce_250k	NUMERIC(38,	2)	,		
nc_inc_loss_dcce_500k	NUMERIC(38,	2)	,		
nc_inc_loss_dcce_750k	NUMERIC(38,	2)	,		
nc_inc_loss_dcce_1m	NUMERIC(38,	2)	,		
nc_inc_loss_dcce	NUMERIC(38,	2)	,		
cat_inc_loss_dcce_le500	NUMERIC(38,	2)	,		
cat_inc_loss_dcce_1000	NUMERIC(38,	2)	,		
cat_inc_loss_dcce_1500	NUMERIC(38,	2)	,		
cat_inc_loss_dcce_2000	NUMERIC(38,	2)	,		
cat_inc_loss_dcce_2500	NUMERIC(38,	2)	,		
cat_inc_loss_dcce_5k	NUMERIC(38,	2)	,		
cat_inc_loss_dcce_10k	NUMERIC(38,	2)	,		
cat_inc_loss_dcce_25k	NUMERIC(38,	2)	,		
cat_inc_loss_dcce_50k	NUMERIC(38,	2)	,		
cat_inc_loss_dcce_100k	NUMERIC(38,	2)	,		
cat_inc_loss_dcce_250k	NUMERIC(38,	2)	,		
cat_inc_loss_dcce_500k	NUMERIC(38,	2)	,		
cat_inc_loss_dcce_750k	NUMERIC(38,	2)	,		
cat_inc_loss_dcce_1m	NUMERIC(38,	2)	,		
cat_inc_loss_dcce	NUMERIC(38,	2)	,		
bilossinc1530	INTEGER ,				
umbilossinc1530	INTEGER ,				
uimbilossinc1530	INTEGER ,				
qualityflgreplacedvin	VARCHAR(3) ,				
qualityflgreplaceddriver	VARCHAR(3) ,				
qualityclaimokflg	INTEGER ,				
qualityclaimunknownvinflg	INTEGER ,				
qualityclaimunknownvinnotlisteddriverflg	INTEGER ,				
qualityclaimpolicytermjoinflg	INTEGER ,				
loaddate	TIMESTAMP 				
)					
partitioned by (month_id INTEGER)					
stored as PARQUET					
location  's3://cse-bi/RedshiftSpectrum/Modeling/Auto/'					
TABLE PROPERTIES ( 'write.parallel'='on' );					
					
/*					
					
insert into external_data_modeling.auto					
select *, cast(to_char(ADD_MONTHS(GetDate(),-1),'yyyymm') as int) month_id from fsbi_dw_spinn.vauto_modeldata_allcov					
					
					
ALTER TABLE external_data_modeling.auto DROP PARTITION  (month_id=202203)					
					
					
select month_id, count(*)	,  max(enddatetm) max_enddatetm				
from external_data_modeling.auto					
where month_id in (202101,202112, 202201, 202202)					
group by month_id;					
					
					
select  count(*)	,  max(enddatetm) max_enddatetm				
from modeling.vauto_modeldata_allcov_20220104	;				
					
select  count(*)	,  max(enddatetm) max_enddatetm				
from modeling.vauto_modeldata_allcov_20220201	;				
					
					
select 					
replace(replace(replace(values,'[',''),']',''),'"','') month_id,					
select * from external_data_modeling.auto where month_id='+cast(month_id as varchar) +' limit 100;'					
from SVV_EXTERNAL_PARTITIONS					
where schemaname='external_data_modeling'					
and tablename='auto'					
order by month_id					

*/